{
  "openapi": "3.0.2",
  "info": {
    "title": "shipcloud.io API",
    "description": "Everything about the shipcloud api",
    "termsOfService": "https://www.shipcloud.io/en/terms_and_conditions",
    "contact": {
      "name": "Developer Support",
      "email": "developers@shipcloud.io"
    },
    "version": "1.0"
  },
  "servers": [{
    "url": "https://api.shipcloud.io/v1",
    "description": "There is only one api url. Destinction between sandbox and live requests is done by the api key"
  }],
  "paths": {
    "/addresses": {
      "get": {
        "description": "Getting a list of addresses",
        "parameters": [
          {
            "name": "care_of",
            "in": "path",
            "description": "Filter addresses by care_of",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "city",
            "in": "path",
            "description": "Filter addresses by city",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "company",
            "in": "path",
            "description": "Filter addresses by company name",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "country",
            "in": "path",
            "description": "Filter addresses by country code",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "first_name",
            "in": "path",
            "description": "Filter addresses by first name",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "last_name",
            "in": "path",
            "description": "Filter addresses by last name",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "page",
            "in": "path",
            "description": "Number of page that should be returned",
            "schema": {
              "type": "integer"
            }
          },
          {
            "name": "per_page",
            "in": "path",
            "description": "Number of items that should be shown on a page (default value is 100)",
            "schema": {
              "type": "integer",
              "default": 100
            }
          },
          {
            "name": "phone",
            "in": "path",
            "description": "Filter addresses by phone number",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "street",
            "in": "path",
            "description": "Filter addresses by street name",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "street_no",
            "in": "path",
            "description": "Filter addresses by house number",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "zip_code",
            "in": "path",
            "description": "Filter addresses by zip code",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "List of addresses",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/address_with_id"
                  }
                },
                "examples": {
                  "list_of_addresses_example": {
                    "$ref": "#/components/examples/list_of_addresses_with_id_example"
                  }
                }
              }
            }
          }
        }
      },
      "post": {
        "description": "Creating an address",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/address"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "An address was created",
            "content": {
              "application/json": {
                "schema": {
                  "allOf": [
                    {
                      "$ref": "#/components/schemas/address_with_id"
                    },
                    {
                      "description": "An address that was created. It is referenced by its id."
                    }
                  ]
                },
                "examples": {
                  "address_with_id_example": {
                    "$ref": "#/components/examples/address_with_id_example"
                  }
                }
              }
            }
          }

        }
      }
    },
    "/addresses/{id}": {
      "parameters": [
        {
          "name": "id",
          "in": "path",
          "required": true,
          "description": "The identifier of a previously created address",
          "schema": {
            "type": "string"
          }
        }
      ],
      "get": {
        "description": "Returns a single address based on its identifier",
        "responses": {
          "200": {
            "description": "Detailed information about a single address",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/address_with_id"
                },
                "examples": {
                  "address_with_id_example": {
                    "$ref": "#/components/examples/address_with_id_example"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/carriers": {
      "get": {
        "description": "Returns all carriers for the user associated with the api key",
        "responses": {
          "200": {
            "description": "A list of carriers.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "name": {
                        "type": "string",
                        "description": "key for referencing the carrier within shipcloud"
                      },
                      "display_name": {
                        "type": "string",
                        "description": "name of the carrier you can use to display it in your application"
                      },
                      "services": {
                        "type": "array",
                        "items": {
                          "type": "string",
                          "description": "key for referencing the service within shipcloud",
                          "enum": [
                            "standard",
                            "one_day",
                            "one_day_early",
                            "returns",
                            "cargo_international_express",
                            "dhl_europaket",
                            "dhl_prio",
                            "dhl_warenpost",
                            "dpag_warenpost",
                            "dpag_warenpost_signature",
                            "dpag_warenpost_untracked",
                            "gls_express_0800",
                            "gls_express_0900",
                            "gls_express_1000",
                            "gls_express_1200",
                            "ups_express_1200"
                          ],
                          "default": "standard"
                        }
                      },
                      "package_types": {
                        "type": "array",
                        "items": {
                          "type": "string",
                          "description": "key for referencing the package type within shipcloud",
                          "enum": ["parcel", "bulk", "letter", "books", "parcel_letter"],
                          "default": "parcel"
                        }
                      },
                      "additional_services": {
                        "type": "array",
                        "items": {
                          "type": "string",
                          "enum": [
                            "saturday_delivery",
                            "angel_de_delivery_date_time",
                            "advance_notice",
                            "hermes_identservice",
                            "drop_authorization",
                            "dpd_food",
                            "delivery_date",
                            "delivery_note",
                            "delivery_time",
                            "cash_on_delivery",
                            "gls_guaranteed24service",
                            "dhl_gogreen",
                            "dhl_ident_check",
                            "premium_international",
                            "visual_age_check",
                            "dhl_endorsement",
                            "dhl_named_person_only",
                            "dhl_parcel_outlet_routing",
                            "ups_adult_signature",
                            "ups_direct_delivery_only"
                          ],
                          "description": "key to identify the additional service"
                        }
                      }
                    },
                    "required": [
                      "name",
                      "display_name",
                      "services",
                      "package_types",
                      "additional_services"
                    ],
                    "additionalProperties": false
                  }
                },
                "examples": {
                  "carriers_call_example": {
                    "value": [
                      {
                        "name": "dhl",
                        "display_name": "Deutsche Post DHL",
                        "services": [
                          "standard",
                          "returns"
                        ],
                        "package_types": [
                          "parcel",
                          "bulk"
                        ],
                        "additional_services": [
                          "advance_notice"
                        ]
                      },
                      {
                        "name": "dpag",
                        "display_name": "Deutsche Post",
                        "services": [
                          "standard"
                        ],
                        "package_types": [
                          "letter",
                          "parcel_letter",
                          "books"
                        ],
                        "additional_services": []
                      },
                      {
                        "name": "dpd",
                        "display_name": "DPD - Dynamic Parcel Distribution",
                        "services": [
                          "standard",
                          "returns",
                          "one_day",
                          "one_day_early"
                        ],
                        "package_types": [
                          "parcel",
                          "parcel_letter"
                        ],
                        "additional_services": [
                          "advance_notice",
                          "drop_authorization",
                          "saturday_delivery"
                        ]
                      }
                    ]
                  }
                }
              }
            }
          }
        }
      }
    },
    "/default_returns_address": {
      "get": {
        "description": "Getting the default returns address",
        "responses": {
          "200": {
            "description": "Detailed information the default returns address",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/address_with_id"
                },
                "examples": {
                  "address_with_id_example": {
                    "$ref": "#/components/examples/address_with_id_example"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/default_shipping_address": {
      "get": {
        "description": "Getting the default shipping address",
        "responses": {
          "200": {
            "description": "Detailed information the default shipping address",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/address_with_id"
                },
                "examples": {
                  "address_with_id_example": {
                    "$ref": "#/components/examples/address_with_id_example"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/invoice_address": {
      "get": {
        "description": "Getting the invoice address",
        "responses": {
          "200": {
            "description": "Detailed information the invoice address",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/address_with_id"
                },
                "examples": {
                  "address_with_id_example": {
                    "$ref": "#/components/examples/address_with_id_example"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/shipment_quotes": {
      "post": {
        "description": "Find out how much we will charge you for a specific shipment when using shipcloud carrier contracts.",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "carrier": {
                    "type": "string",
                    "enum": [
                      "angel_de",
                      "cargo_international",
                      "dhl",
                      "dhl_express",
                      "dpag",
                      "dpd",
                      "gls",
                      "go",
                      "hermes",
                      "iloxx",
                      "parcel_one",
                      "ups"
                    ],
                    "description": "acronym of the carrier you want to use"
                  },
                  "service": {
                    "type": "string",
                    "enum": [
                      "standard",
                      "one_day",
                      "one_day_early",
                      "returns",
                      "cargo_international_express",
                      "dhl_europaket",
                      "dhl_prio",
                      "dhl_warenpost",
                      "dpag_warenpost",
                      "dpag_warenpost_signature",
                      "dpag_warenpost_untracked",
                      "gls_express_0800",
                      "gls_express_0900",
                      "gls_express_1000",
                      "gls_express_1200",
                      "ups_express_1200"
                    ],
                    "default": "standard",
                    "description": "The service that should be used for the shipment."
                  },
                  "to": {
                    "allOf": [
                      {
                        "$ref": "#/components/schemas/address"
                      },
                      {
                        "description": "the receivers address"
                      }
                    ]
                  },
                  "from": {
                    "allOf": [
                      {
                        "$ref": "#/components/schemas/address"
                      },
                      {
                        "description": "the senders address"
                      }
                    ]
                  },
                  "package": {
                    "$ref": "#/components/schemas/package"
                  }
                },
                "required": [
                  "carrier",
                  "service",
                  "to",
                  "package"
                ],
                "additionalProperties": false
              }
            }
          }
        }
      }

    },
    "/shipments": {
      "get": {
        "description": "Returns a list of shipments",
        "responses": {
          "200": {
            "description": "A list of shipments.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/shipment_object"
                  }
                },
                "examples": {
                  "shipments_list_example": {
                    "value": [
                      {
                        "carrier": "dhl",
                        "carrier_tracking_no": "84168117830018",
                        "created_at": "2013-04-16T10:43:04Z",
                        "from": {
                          "company": "Musterfirma",
                          "first_name": "Hans",
                          "last_name": "Meier",
                          "street": "Musterstraße",
                          "street_no": "22",
                          "city": "Musterstadt",
                          "zip_code": "12345",
                          "country": "DE"
                        },
                        "id": "3a186c51d4281acbecf5ed38805b1db92a9d668b",
                        "label_url": "https://shipping-labels.shipcloud.io/shipments/01370b4d/199f803bf8/label/shipping_label_199f803bf8.pdf",
                        "notification_email": "receiver@notification.com",
                        "packages": [{
                          "id": "3af8f7e5af196e1950deebd389a87406e1e5bb80",
                          "weight": 1.5,
                          "length": 10.0,
                          "width": 6.0,
                          "height": 8.0,
                          "tracking_events": [{
                              "timestamp": "2013-05-26T16:55:24+02:00",
                              "location": "Hamburg, Deutschland",
                              "status": "delivered",
                              "details": "Die Sendung wurde erfolgreich zugestellt."
                            },
                            {
                              "timestamp": "2013-05-26T08:12:12+02:00",
                              "location": "Hamburg, Deutschland",
                              "status": "out_for_delivery",
                              "details": "Die Sendung wurde in das Zustellfahrzeug geladen."
                            },
                            {
                              "timestamp": "2013-05-25T11:46:34+02:00",
                              "location": "Hamburg, Deutschland",
                              "status": "transit",
                              "details": "Die Sendung wurde im Start-Paketzentrum bearbeitet."
                            }
                          ]
                        }],
                        "price": 3.4,
                        "reference_number": "ref123456",
                        "service": "standard",
                        "shipper_notification_email": "shipper@notification.com",
                        "to": {
                          "company": "Receiver Inc.",
                          "first_name": "Max",
                          "last_name": "Mustermann",
                          "street": "Beispielstrasse",
                          "street_no": "42",
                          "city": "Hamburg",
                          "zip_code": "22100",
                          "state": null,
                          "country": "DE"
                        },
                        "tracking_url": "https://track.shipcloud.io/3a186c51d4"
                      }
                    ]
                  }
                }
              }
            }
          }
        }
      },
      "post": {
        "description": "Create a shipment",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "allOf": [
                  {
                    "$ref": "#/components/schemas/shipment"
                  },
                  {
                    "type": "object",
                    "description": "!!! TBD !!!",
                    "properties": {
                      "package": {
                        "$ref": "#/components/schemas/package"
                      }
                    }
                  }
                ]
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "A shipment was created",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/shipment_response_object"
                },
                "examples": {
                  "shipment_response_example": {
                    "$ref": "#/components/examples/shipment_response_example"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/shipments/{id}": {
      "parameters": [
        {
          "name": "id",
          "in": "path",
          "required": true,
          "description": "a shipment identifier",
          "schema": {
            "type": "string"
          }
        }
      ],
      "get": {
        "description": "Returns a single shipment based on the id",
        "responses": {
          "200": {
            "description": "Detailed information about a single shipment",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/shipment_object"
                }
              }
            }
          }
        }
      },
      "put": {
        "description": "Updates a single shipment based on the id",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "allOf": [
                  {
                    "$ref": "#/components/schemas/shipment"
                  },
                  {
                    "type": "object",
                    "description": "!!! TBD !!!",
                    "properties": {
                      "package": {
                        "$ref": "#/components/schemas/package"
                      }
                    }
                  }
                ]
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "Updated information about a single shipment",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/shipment_response_object"
                },
                "examples": {
                  "shipment_response_example": {
                    "$ref": "#/components/examples/shipment_response_example"
                  }
                }
              }
            }
          }
        }
      },
      "delete": {
        "description": "Deletes a single shipment. **Notice:**  Prepared shipments (where `create_shipping_label` is `false`) can be deleted at any time, because no transaction with the carrier has happened until this point and no actual shipping label has been created. In case you've created a shipping label you can delete it before the cutoff time of the carrier. Cutoff times differ from carrier to carrier and are some time between 5pm and 8pm.",
        "responses": {
          "204": {
            "description": "Shipment was deleted successfully",
            "content": {
              "application/json": {
                "examples": {
                  "empty_response_example": {
                    "value": {}
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "examples": {
      "address_with_id_example": {
        "value": {
          "id": "1c81efb7-9b95-4dd8-92e3-cac1bca3df6f",
          "first_name": "Max",
          "last_name": "Mustermann",
          "street": "Musterstraße",
          "street_no": "42",
          "zip_code": "12345",
          "city": "Musterstadt",
          "country": "DE",
          "email": "max@mustermann.baz",
          "phone": "+491234567890"
        }
      },
      "list_of_addresses_with_id_example": {
        "value": [
          {
            "id": "1c81efb7-9b95-4dd8-92e3-cac1bca3df6f",
            "first_name": "Max",
            "last_name": "Mustermann",
            "street": "Musterstraße",
            "street_no": "42",
            "zip_code": "12345",
            "city": "Musterstadt",
            "country": "DE",
            "email": "max@mustermann.baz",
            "phone": "+491234567890"
          }
        ]
      },
      "shipment_response_example": {
        "value": {
          "id": "3a186c51d4281acbecf5ed38805b1db92a9d668b",
          "carrier_tracking_no": "84168117830018",
          "tracking_url": "https://track.shipcloud.io/3a186c51d4",
          "label_url": "https://shipping-labels.shipcloud.io/shipments/01370b4d/199f803bf8/label/shipping_label_199f803bf8.pdf",
          "price": 3.4
        }
      }
    },
    "schemas": {
      "address": {
        "type": "object",
        "properties": {
          "care_of": {
            "type": "string"
          },
          "city": {
            "type": "string"
          },
          "company": {
            "type": "string"
          },
          "country": {
            "type": "string",
            "description": "Country as uppercase ISO 3166-1 alpha-2 code"
          },
          "first_name": {
            "type": "string"
          },
          "last_name": {
            "type": "string"
          },
          "state": {
            "type": "string"
          },
          "street": {
            "type": "string"
          },
          "street_no": {
            "type": "string"
          },
          "zip_code": {
            "type": "string"
          },
          "phone": {
            "type": "string",
            "description": "telephone number (mandatory when using UPS and the following terms apply: service is one_day or one_day_early or ship to country is different than ship from country)"
          },
          "email": {
            "type": "string",
            "description": "email address for this person. Some carrier are using the email address to notify it about a shipment"
          }
        },
        "required": ["last_name", "street", "street_no", "city", "zip_code", "country"],
        "additionalProperties": false
      },
      "address_with_id": {
        "allOf": [
          {
            "type": "object",
            "description": "address where the carrier should pick up shipments",
            "properties": {
              "id": {
                "type": "string",
                "description": "identifier of a previously created address"
              }
            },
            "required": ["id"],
            "additionalProperties": false
          },
          {
            "$ref": "#/components/schemas/address"
          }
        ]
      },
      "label": {
        "type": "object",
        "properties": {
          "format": {
            "type": "string",
            "enum": [
              "pdf_100x70mm",
              "pdf_a5",
              "pdf_a6",
              "pdf_a7",
              "zpl2_100x70mm_203dpi",
              "zpl2_103x199mm_203dpi"
            ],
            "description": "defines the format that the returned label should have"
          },
          "size": {
            "type": "string",
            "enum": [
              "A5",
              "A6",
              "A7",
              "100x70mm"
            ],
            "description": "defines the size that the returned label should have",
            "deprecated": true
          }
        },
        "additionalProperties": false,
        "description": "label specific definitions"
      },
      "package": {
        "type": "object",
        "properties": {
          "height": {
            "type": "number",
            "description": "Height of the parcel in cm"
          },
          "length": {
            "type": "number",
            "description": "Length of the parcel in cm"
          },
          "weight": {
            "type": "number",
            "description": "Weight of the parcel in kg"
          },
          "width": {
            "type": "number",
            "description": "Width of the parcel in cm"
          },
          "declared_value": {
            "type": "object",
            "description": "Object that is used for booking an additional insurance at the carrier (if applicable)",
            "properties": {
              "amount": {
                "type": "number",
                "description": "The total amount of the goods value that an additional insurance should be booked for"
              },
              "currency": {
                "type": "string",
                "description": "The currency used. Currently onl EUR is applicable"
              }
            }
          }
        },
        "required": ["width", "height", "length", "weight"],
        "additionalProperties": false,
        "description": "defines package dimensions"
      },
      "package_with_id": {
        "allOf": [
          {
            "properties": {
              "id": {
                "type": "string",
                "description": "the id of this package"
              },
              "tracking_events": {
                "type": "array",
                "items": {
                  "type": "object",
                  "properties": {
                    "timestamp": {
                      "type": "date-time",
                      "description": "timestamp of when this event occured"
                    },
                    "location": {
                      "type": "string",
                      "description": "location of the package at this moment"
                    },
                    "status": {
                      "type": "string",
                      "enum": [
                        "label_created",
                        "picked_up",
                        "delivered",
                        "not_delivered",
                        "transit",
                        "exception",
                        "out_for_delivery",
                        "destroyed",
                        "unknown", "canceled"
                      ],
                      "description": "key describing the status"
                    },
                    "details": {
                      "type": "string",
                      "description": "message the carrier sends to describe the package status"
                    }
                  },
                  "required": ["timestamp", "location", "status", "details"],
                  "additionalProperties": false
                }
              }
            },
            "required": ["id"],
            "additionalProperties": false
          },
          {
            "$ref": "#/components/schemas/package"
          }
        ]
      },
      "pickup": {
        "type": "object",
        "description": "for some carriers a pickup has to be requested when creating a shipment",
        "properties": {
          "pickup_time": {
            "type": "object",
            "properties": {
              "earliest": {
                "type": "string",
                "format": "date-time"
              },
              "latest": {
                "type": "string",
                "format": "date-time"
              }
            },
            "description": "defines a time window in which the carrier should pickup shipments",
            "required": ["earliest", "latest"],
            "additionalProperties": false
          },
          "pickup_address": {
            "$ref": "#/components/schemas/address_with_id"
          }
        }
      },
      "shipment": {
        "type": "object",
        "properties": {
          "carrier": {
            "type": "string",
            "enum": [
              "angel_de",
              "cargo_international",
              "dhl",
              "dhl_express",
              "dpag",
              "dpd",
              "gls",
              "go",
              "hermes",
              "iloxx",
              "parcel_one",
              "ups"
            ],
            "description": "acronym of the carrier you want to use"
          },
          "to": {
            "allOf": [
              {
                "$ref": "#/components/schemas/address"
              },
              {
                "description": "the receivers address"
              }
            ]
          },
          "from": {
            "allOf": [
              {
                "$ref": "#/components/schemas/address"
              },
              {
                "description": "If missing, the default sender address (if defined in your shipcloud account) will be used"
              }
            ]
          },
          "cover_address": {
            "allOf": [
              {
                "$ref": "#/components/schemas/address"
              },
              {
                "description": "Overwrites the sender address on the shipping label"
              }
            ]
          },
          "service": {
            "type": "string",
            "enum": [],
            "default": "standard",
            "description": "The service that should be used for the shipment."
          },
          "reference_number": {
            "type": "string",
            "description": "a reference number (max. 30 characters) that you want this shipment to be identified with. You can use this afterwards to easier find the shipment in the shipcloud.io backoffice"
          },
          "description": {
            "type": "string",
            "description": "text that describes the contents of the shipment. This parameter is mandatory if you're using UPS and the following conditions are true: from and to countries are not the same; from and/or to countries are not in the EU; from and to countries are in the EU and the shipments service is not 'standard'. The parameter is also mandatory when using DHL Express as carrier."
          },
          "label": {
            "$ref": "#/components/schemas/label"
          },
          "notification_email": {
            "type": "string",
            "description": "email address that we should notify once there's an update for this shipment"
          },
          "incoterm": {
            "type": "string",
            "enum": [
              "ddp",
              "ddp_untaxed",
              "dap",
              "dap_cleared",
              "ddu",
              "ddu_cleared"
            ]
          },
          "additional_services": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "name": {
                  "type": "string",
                  "enum": [
                    "advance_notice",
                    "angel_de_delivery_date_time",
                    "cash_on_delivery",
                    "delivery_date",
                    "delivery_note",
                    "delivery_time",
                    "dhl_endorsement",
                    "dhl_gogreen",
                    "dhl_ident_check",
                    "dhl_named_person_only",
                    "dhl_parcel_outlet_routing",
                    "dpd_food",
                    "drop_authorization",
                    "gls_guaranteed24service",
                    "hermes_identservice",
                    "premium_international",
                    "saturday_delivery",
                    "ups_adult_signature",
                    "ups_direct_delivery_only",
                    "visual_age_check"
                  ],
                  "description": "key to identify the additional service"
                },
                "properties": {
                  "type": "object",
                  "properties": {
                    "amount": {
                      "type": "number"
                    },
                    "bank_account_holder": {
                      "type": "string"
                    },
                    "bank_account_number": {
                      "type": "string"
                    },
                    "bank_code": {
                      "type": "string"
                    },
                    "bank_name": {
                      "type": "string"
                    },
                    "currency": {
                      "type": "string"
                    },
                    "date": {
                      "type": "string"
                    },
                    "date_of_birth": {
                      "type": "string"
                    },
                    "email": {
                      "type": "string"
                    },
                    "first_name": {
                      "type": "string"
                    },
                    "id_type": {
                      "type": "string",
                      "enum": [
                        "german_identity_card",
                        "german_passport",
                        "international_passport"
                      ],
                      "description": "Type of ID document that should be used for verifying a Hermes recipient"
                    },
                    "id_number": {
                      "type": "string",
                      "description": "ID number from the document"
                    },
                    "language": {
                      "type": "string",
                      "description": "language the customer should be notified in (ISO-639-1 format)"
                    },
                    "last_name": {
                      "type": "string"
                    },
                    "minimum_age": {
                      "type": "string"
                    },
                    "phone": {
                      "type": "string"
                    },
                    "reference1": {
                      "type": "string",
                      "description": "Text that should be displayed as the reason for transfer"
                    },
                    "sms": {
                      "type": "string"
                    },
                    "time_of_day_earliest": {
                      "type": "string"
                    },
                    "time_of_day_latest": {
                      "type": "string"
                    }
                  }
                }
              }
            },
            "required": [
              "name"
            ],
            "additionalProperties": false
          },
          "pickup": {
            "$ref": "#/components/schemas/pickup"
          },
          "customs_declaration": {
            "type": "object",
            "description": "declaration of customs related information",
            "properties": {
              "contents_type": {
                "type": "string",
                "enum": [
                  "commercial_goods",
                  "commercial_sample",
                  "documents",
                  "gift",
                  "returned_goods"
                ],
                "description": "Type of contents"
              },
              "contents_explanation": {
                "type": "string",
                "description": "description of contents. Mandatory if contents_type is 'commercial_goods. Max 256 characters, when using DHL as your carrier'"
              },
              "currency": {
                "type": "string",
                "description": "a valid ISO 4217 curreny code"
              },
              "additional_fees": {
                "type": "number",
                "description": "additional custom fees to be payed"
              },
              "drop_off_location": {
                "type": "string",
                "description": "location where the package will be dropped of with the carrier"
              },
              "exporter_reference": {
                "type": "string",
                "description": "a note for the exporter"
              },
              "importer_reference": {
                "type": "string",
                "description": "a note for the importer"
              },
              "posting_date": {
                "type": "string",
                "format": "date",
                "description": "date of commital at carrier"
              },
              "invoice_number": {
                "type": "string",
                "description": "invoice number for the order"
              },
              "total_value_amount": {
                "type": "number",
                "minimum": 0,
                "maximum": 1000,
                "description": "the overall value of the shipments' contents"
              },
              "items": {
                "type": "array",
                "description": "array of item objects",
                "items": {
                  "type": "object",
                  "properties": {
                    "origin_country": {
                      "type": "string",
                      "description": "Country as uppercase ISO 3166-1 alpha-2 code"
                    },
                    "description": {
                      "type": "string",
                      "description": "a description of the item"
                    },
                    "hs_tariff_number": {
                      "type": "string",
                      "description": "customs tariff number. See https://en.wikipedia.org/wiki/Harmonized_System#Tariffs_by_region for detailed information on region specific tariff numbers",
                      "maxLength": 10
                    },
                    "quantity": {
                      "type": "integer",
                      "description": "Number that defines how many items of this kind are in the shipment"
                    },
                    "value_amount": {
                      "type": "string",
                      "description": "The total value for items of this kind"
                    },
                    "net_weight": {
                      "type": "number",
                      "description": "Total weight for items of this kind"
                    }
                  },
                  "required": [
                    "origin_country",
                    "description",
                    "quantity",
                    "value_amount",
                    "net_weight"
                  ],
                  "additionalProperties": false
                }
              }
            },
            "required": [
              "contents_type",
              "currency",
              "total_value_amount",
              "items"
            ],
            "additionalProperties": false
          },
          "create_shipping_label": {
            "type": "boolean",
            "description": "determines if a shipping label should be created at the carrier (this means you will be charged when using the production api key)"
          },
          "metadata": {
            "type": "object",
            "description": "here you can save additional data that you want to be associated with the shipment. Any combination of key-value pairs is possible",
            "additionalProperties": true
          }
        },
        "required": [
          "carrier",
          "to",
          "package"
        ],
        "additionalProperties": false
      },
      "shipment_object": {
        "allOf": [
          {
            "type": "object",
            "description": "!!! TBD !!!",
            "properties": {
              "id": {
                "type": "string",
                "description": "identifier of the shipment"
              },
              "carrier_tracking_no": {
                "type": "string",
                "description": "the original tracking number that can be used on the carriers website"
              },
              "created_at": {
                "type": "date-time",
                "description": "timestamp the shipment was created"
              },
              "label_url": {
                "type": "string",
                "description": "URL where you can download the label in pdf format"
              },
              "packages": {
                "type": "array",
                "items": {
                  "allOf": [
                    {
                      "$ref": "#/components/schemas/package_with_id"
                    }
                  ]
                }
              },
              "price": {
                "type": "number",
                "description": "price that we're going to charge you (exl. VAT)"
              },
              "shipper_notification_email": {
                "type": "string",
                "description": "email address of the shipper who should be notified of a change of shipment status by shipcloud"
              },
              "tracking_url": {
                "type": "string",
                "description": "URL you can send your customers so they can track this shipment"
              }
            }
          },
          {
            "$ref": "#/components/schemas/shipment"
          }
        ],
        "required": [
          "id",
          "carrier",
          "created_at",
          "tracking_url",
          "from",
          "to",
          "packages",
          "price",
          "reference_number",
          "service"
        ],
        "additionalProperties": false
      },
      "shipment_response_object": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "description": "the shipment id that can be used for requesting info about a shipment or tracking it"
          },
          "carrier_tracking_no": {
            "type": "string",
            "description": "the original tracking number that can be used on the carriers website"
          },
          "tracking_url": {
            "type": "string",
            "description": "URL you can send your customers so they can track this shipment"
          },
          "label_url": {
            "type": "string",
            "description": "URL where you can download the label in pdf format"
          },
          "price": {
            "type": "number",
            "description": "Price that you're going to be charged with (exl. VAT). You will get a price of 0.0 when using the sandbox or your own carrier contracts."
          }
        },
        "required": ["id", "tracking_url", "label_url", "price"],
        "additionalProperties": false
      }
    },
    "securitySchemes": {
      "basic_auth": {
        "type": "http",
        "scheme": "basic"
      }
    }
  },
  "security": {
    "basic_auth": []
  },
  "externalDocs": {
    "description": "Find more info at the shipcloud developer portal",
    "url": "https://developers.shipcloud.io"
  }
}
